version: "3"
services:
  nodered: 
    build: ./nodered
    image: localbuild/nodered:feb2023
    container_name: nodered
    restart: always
    environment:
      - L_HOST=192.168.1.130
      - C_HOST=137.184.1.44
    ports: 
      - "1880:1880"
    volumes:
      - noderedData:/data
    networks:
      - edge
    devices:
      - /dev/gpiomem:/dev/gpiomem

  gpiod:
    image: corbosman/pigpiod
    container_name: gpiod
    privileged: true
    restart: unless-stopped
    networks:
      - edge

  grafana:
    build: ./grafana
    image: localbuild/grafana:abr2023
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes: 
      - grafanaData2:/var/lib/grafana
      - grafanaConfig2:/etc/grafana
      - grafanaIcons:/usr/share/grafana/public/img/icons
      - grafanaMaps:/usr/share/grafana/public/maps
    networks:
      - edge
  influxdb:
    build: ./influxdb
    image: localbuild/influxdb:feb2023_1.8
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=agro01
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      
#      DOCKER_INFLUXDB_INIT_USERNAME: admin
#      DOCKER_INFLUXDB_INIT_PASSWORD: admin
#      DOCKER_INFLUXDB_INIT_ORG: agrotec
#      DOCKER_INFLUXDB_INIT_BUCKET: agro01
#      DOCKER_INFLUXDB_INIT_RETENTION: 1w
#      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 
    ports:
      - "8082:8082"
      - "8086:8086"
      - "8089:8089"
    volumes:
      - influxData:/var/lib/influxdb
    networks: 
      - edge

#Create internal link network for Containers
networks:
  edge:

#Create Volumes for persistent Storage
volumes:
  grafanaData2:
  noderedData:
  influxData:
  grafanaConfig2:
  grafanaIcons:
  grafanaMaps:

